version: '3.8'

services:
  dotnetapp:
    build: 
      context: ../src/.
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      ASPNETCORE_ENVIRONMENT: Development
      # - ASPNETCORE_URLS=http://+:80
      ConnectionStrings__DefaultConnection: server=mysql;port=3306;database=eventom;user=root;password=12345678
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - /root/nginx.conf:/etc/nginx/nginx.conf:ro
      - /root/certbot/www/:/var/www/certbot/:ro
    depends_on:
      - dotnetapp
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /root/certbot/www/:/var/www/certbot/:rw
      - /root/certbot/conf/:/etc/letsencrypt/:rw 

  mysql:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_ROOT_HOST: 127.0.0.1
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
